save_path: "src/state_action_record_ros2/state_action_record/datasets/data.hdf5" # root dir is workspace
data_classes: ['obs', 'act']
freq: 5
start_waiting_time: 10 # Wait for a while so the current state can be updated first

